plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
}

group = 'io.github.jebai'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11

    withJavadocJar()
    withSourcesJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifactId = 'security-tools'

            pom {
                name = 'security-tools'
                description = 'A security tools library'
                url = 'https://github.com/jebai/security-tools'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'jebai'
                        name = 'jebai'
                        email = 'jebai@example.com'
                    }
                }

                scm {
                    connection = 'scm:git@github.com:jebai/security-tools.git'
                    developerConnection = 'scm:git@github.com:jebai/security-tools.git'
                    url = 'https://github.com/jebai/security-tools'
                }
            }
        }
    }

    repositories {
        maven {
            name = 'MavenCentral'
            url = 'https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/'
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
