plugins {
    id 'java-library'
    id 'com.vanniktech.maven.publish'
}

group = 'io.github.jebai'
def artifactId = 'security-tools'
version = '1.0.5'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

mavenPublishing {
    coordinates(group, artifactId, version)

    pom {
        name = artifactId
        description = 'A security tools library'
        url = 'https://github.com/jebai/security-tools'

        licenses {
            license {
                name = 'MIT License'
                url = 'https://opensource.org/licenses/MIT'
            }
        }

        developers {
            developer {
                id = 'jebai'
                name = 'jebai'
                email = 'jebai@qq.com'
            }
        }

        scm {
            connection = 'scm:git@github.com:jebai/security-tools.git'
            developerConnection = 'scm:git@github.com:jebai/security-tools.git'
            url = 'https://github.com/jebai/security-tools'
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}