plugins {
    id 'java-library'
    id 'com.vanniktech.maven.publish' version '0.36.0'
}

group = 'io.github.jebai'
version = '1.0.4'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

mavenPublishing {
    coordinates("io.github.jebai", "security-tools", "1.0.4")

    pom {
        name = 'security-tools'
        description = 'A security tools library'
        url = 'https://github.com/jebai/security-tools'

        licenses {
            license {
                name = 'MIT License'
                url = 'https://opensource.org/licenses/MIT'
            }
        }

        developers {
            developer {
                id = 'jebai'
                name = 'jebai'
                email = 'jebai@example.com'
            }
        }

        scm {
            connection = 'scm:git@github.com:jebai/security-tools.git'
            developerConnection = 'scm:git@github.com:jebai/security-tools.git'
            url = 'https://github.com/jebai/security-tools'
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
